Areas/Admin/Controllers/WidgetsCustomFormController.cs
using Grand.Business.Core.Interfaces.Common.Configuration;
using Grand.Business.Core.Interfaces.Common.Localization;
using Grand.Business.Core.Interfaces.Storage;
using Grand.Business.Core.Utilities.Common.Security;
using Grand.Web.Common.Controllers;
using Grand.Web.Common.DataSource;
using Grand.Web.Common.Filters;
using Grand.Web.Common.Security.Authorization;
using Microsoft.AspNetCore.Mvc;
using Widgets.CustomForm.Models;
using Widgets.CustomForm.Services;

namespace Widgets.CustomForm.Areas.Admin.Controllers
{
    [AuthorizeAdmin]
    [Area("Admin")]
    [PermissionAuthorize(PermissionSystemName.Widgets)]
    public class WidgetsCustomFormController: BasePluginController
    {
        #region fields
        private readonly IPictureService _pictureService;
        private readonly ITranslationService _translationService;
        private readonly ICustomFormService _requestService;
        private readonly ILanguageService _languageService;
        private readonly ISettingService _settingService;
        private readonly CustomFormWidgetSettings _requestWidgetSettings;
        #endregion
        public WidgetsCustomFormController(IPictureService pictureService,
            ITranslationService translationService,
            ICustomFormService requestService,
            ILanguageService languageService,
            ISettingService settingService,
            CustomFormWidgetSettings requestWidgetSettings)
        {
            this._pictureService = pictureService;
            this._translationService = translationService;
            this._requestService = requestService;
            this._languageService = languageService;
            this._settingService = settingService;
            this._requestWidgetSettings = requestWidgetSettings;
        }


        public IActionResult Configure()
        {
            var model = new ConfigurationModel();
            model.DisplayOrder = _requestWidgetSettings.DisplayOrder;
            model.CustomerGroups = _requestWidgetSettings.LimitedToGroups?.ToArray();
            model.Stores = _requestWidgetSettings.LimitedToStores?.ToArray();
            return View(model);
        }

        [HttpPost]
        public IActionResult Configure(ConfigurationModel model)
        {
            _requestWidgetSettings.DisplayOrder = model.DisplayOrder;
            _requestWidgetSettings.LimitedToGroups = model.CustomerGroups == null ? new List<string>() : model.CustomerGroups.ToList();
            _requestWidgetSettings.LimitedToStores = model.Stores == null ? new List<string>() : model.Stores.ToList();
            _settingService.SaveSetting(_requestWidgetSettings);
            return Json("Ok");
        }


        [HttpPost]
        public async Task<IActionResult> List(DataSourceRequest command)
        {
            var requests = await _requestService.GetRequests();

            var items = new List<CustomFormInListModel>();
            foreach (var x in requests)
            {
                var model = x.ToListModel();
                //var picture = await _pictureService.GetPictureById(x.PictureId);
                //if (picture != null)
                //{
                //    model.PictureUrl = await _pictureService.GetPictureUrl(picture, 150);
                //}
                items.Add(model);
            }
            var gridModel = new DataSourceResult {
                Data = items,
                Total = requests.Count
            };
            return Json(gridModel);
        }

        public async Task<IActionResult> Create()
        {
            var model = new CustomFormModel();
            //locales
            await AddLocales(_languageService, model.Locales);

            return View(model);
        }

        [HttpPost, ArgumentNameFilter(KeyName = "save-continue", Argument = "continueEditing")]
        public async Task<IActionResult> Create(CustomFormModel model, bool continueEditing)
        {
            if (ModelState.IsValid)
            {
                var request = model.ToEntity();
                request.Locales = model.Locales.ToLocalizedProperty();

                await _requestService.InsertRequest(request);

                Success(_translationService.GetResource("Widgets.Slider.Added"));
                return continueEditing ? RedirectToAction("Edit", new { id = request.Id }) : RedirectToAction("Configure");

            }
            return View(model);
        }
        public async Task<IActionResult> Edit(string id)
        {
            var slide = await _requestService.GetById(id);
            if (slide == null)
                return RedirectToAction("Configure");

            var model = slide.ToModel();

            //locales
            await AddLocales(_languageService, model.Locales, (locale, languageId) =>
            {
                //locale.Question = slide.GetTranslation(x => x.Question, languageId, false);
                //locale.Answer = slide.GetTranslation(x => x.Answer, languageId, false);
            });

            return View(model);
        }

        [HttpPost, ArgumentNameFilter(KeyName = "save-continue", Argument = "continueEditing")]
        public async Task<IActionResult> Edit(CustomFormModel model, bool continueEditing)
        {
            var request = await _requestService.GetById(model.Id);
            if (request == null)
                return RedirectToAction("Configure");

            if (ModelState.IsValid)
            {
                request = model.ToEntity();
                request.Locales = model.Locales.ToLocalizedProperty();
                await _requestService.UpdateRequest(request);
                Success(_translationService.GetResource("Widgets.CustomForm.Edited"));
                return continueEditing ? RedirectToAction("Edit", new { id = request.Id }) : RedirectToAction("Configure");

            }
            return View(model);
        }

        public async Task<IActionResult> Delete(string id)
        {
            var request = await _requestService.GetById(id);
            if (request == null)
                return Json(new DataSourceResult { Errors = "This form Request not exists" });

            await _requestService.DeleteRequest(request);

            return new JsonResult("");
        }
    }
}

Areas/Admin/Views/WidgetsCustomForm/Configure.cshtml
@model ConfigurationModel
@inject AdminAreaSettings adminAreaSettings
@{
    Layout = "_ConfigurePlugin";
}
@{
    //page title
    ViewBag.Title = Loc["Widgets.CustomForm.Manage"];
}


<div class="row">
    <div class="col-md-12">
        <div class="x_panel light form-fit">
            <div class="x_title">
                <div class="caption">
                    <i class="fa fa-sitemap"></i>
                    @Loc["Widgets.CustomForm.Manage"]
                </div>
                @*<div class="actions btn-group btn-group-devided util-btn-margin-bottom-5">
                    <a href="@Url.Action("Create", "WidgetsCustomForm")" class="btn green">
                        <i class="fa fa-plus"></i><span class="hidden-xs"> @Loc["Admin.Common.AddNew"] </span>
                    </a>
                </div>*@
            </div>
            <div class="x_content">
                <div id="faq-grid"></div>
            </div>
            <div class="x_content form">
                <partial name="_Settings.cshtml" model="Model" />
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $("#faq-grid").kendoGrid({
            dataSource: {
                transport: {
                    read: {
                        url: "@Html.Raw(Url.Action("List", "WidgetsCustomForm"))",
                        type: "POST",
                        dataType: "json"
                    },
                    destroy: {
                        url: "@Html.Raw(Url.Action("Delete", "WidgetsCustomForm"))",
                        type: "POST",
                        dataType: "json",
                    }
                },
                schema: {
                    data: "Data",
                    total: "Total",
                    errors: "Errors",
                    model: {
                        id: "Id",
                    }
                },
                error: function (e) {
                    display_kendoui_grid_error(e);
                    // Cancel the changes
                    this.cancelChanges();
                },
                pageSize: @(adminAreaSettings.DefaultGridPageSize),
                serverPaging: true,
                serverFiltering: true,
                serverSorting: true
            },
            pageable: {
                refresh: true,
                pageSizes: [@(adminAreaSettings.GridPageSizes)]
            },
            editable: {
                confirmation: true,
                mode: "inline"
            },
            scrollable: false,
            columns: [
                {
                    field: "FullName",
                    title: "@Loc["Widgets.CustomForm.Fields.FullName"]",
                    width: 300,
                    template: '<a class="k-link" href="Edit/#=Id#">#=FullName#</a>'
                },
                {
                    field: "Age",
                    title: "@Loc["Widgets.CustomForm.Fields.Age"]",
                    width: 300,
                },
                {
                    field: "LevelOfEducation",
                    title: "@Loc["Widgets.CustomForm.Fields.LevelOfEducation"]",
                    width: 300,
                },
                {
                    field: "Address",
                    title: "@Loc["Widgets.CustomForm.Fields.Address"]",
                    width: 300,
                },
                {
                    field: "WantedCities",
                    title: "@Loc["Widgets.CustomForm.Fields.WantedCities"]",
                    width: 300,
                },
            {
                command: [
                    {
                        name: "destroy",
                        text: "@Loc["Admin.Common.Delete"]"
                    }
                ],
                width: 200
            }
            ]
        });
    });
</script>


Areas/Admin/Views/WidgetsCustomForm/Create.cshtml
@using Widgets.CustomForm.Models
@model CustomFormModel
@{
    //page title
    ViewBag.Title = Loc["Widgets.CustomForm.AddNew"];
    Layout = "_ConfigurePlugin";
}
<form asp-controller="WidgetsCustomForm" asp-action="Create" method="post" id="faqs-form">
    
    <div class="row">
        <div class="col-md-12">
            <div class="x_panel light form-fit">
                <div class="x_title">
                    <div class="caption">
                        <i class="fa fa-sitemap"></i>
                        @Loc["Widgets.CustomForm.AddNew"]
                        <small><i class="fa fa-arrow-circle-left"></i>@Html.ActionLink(Loc["Widgets.CustomForm.BackToList"], "Configure")</small>
                    </div>
                    <div class="actions">
                        <div class="btn-group btn-group-devided util-btn-margin-bottom-5">
                            <button class="btn btn-success" type="submit" name="save"><i class="fa fa-check"></i> @Loc["Admin.Common.Save"] </button>
                            <button class="btn btn-success" type="submit" name="save-continue"><i class="fa fa-check-circle"></i> @Loc["Admin.Common.SaveContinue"] </button>
                        </div>
                    </div>
                </div>
                <div class="x_content form">
                    <partial name="_CreateOrUpdate.cshtml" model="Model" />
                </div>
            </div>
        </div>
    </div>
</form>

Areas/Admin/Views/WidgetsCustomForm/Edit.cshtml
@using Widgets.CustomForm.Models
@model CustomFormModel
@{
    //page title
    ViewBag.Title = Loc["Widgets.CustomForm.Edit"];
    Layout = "_ConfigurePlugin";
}
<form asp-controller="WidgetsCustomForm" asp-action="Edit" method="post" id="faqs-form">
    
    <div class="row">
        <div class="col-md-12">
            <div class="x_panel light form-fit">
                <div class="x_title">
                    <div class="caption">
                        <i class="fa fa-sitemap"></i>
                        @Loc["Widgets.CustomForm.Edit"]
                        <small><i class="fa fa-arrow-circle-left"></i>@Html.ActionLink(Loc["Widgets.CustomForm.BackToList"], "Configure")</small>
                    </div>
                    <div class="actions">
                        <div class="btn-group btn-group-devided util-btn-margin-bottom-5">
                           @* <button class="btn btn-success" type="submit" name="save"><i class="fa fa-check"></i> @Loc["Admin.Common.Save"] </button>
                            <button class="btn btn-success" type="submit" name="save-continue"><i class="fa fa-check-circle"></i> @Loc["Admin.Common.SaveContinue"] </button>*@
                        </div>
                    </div>
                </div>
                <div class="x_content form">
                    <partial name="_CreateOrUpdate.cshtml" model="Model" />
                </div>
            </div>
        </div>
    </div>
</form>

Areas/Admin/Views/WidgetsCustomForm/_CreateOrUpdate.TabInfo.cshtml
@model CustomFormModel

<div class="form-horizontal">

    <div class="form-body">
        <div class="form-group">
            <admin-label asp-for="FullName" />
            <div class="col-md-9 col-sm-9">
                
                @Html.Label(Model.FullName)
                
                <span asp-validation-for="Stores"></span>
            </div>
        </div>
    </div>

    <div class="form-body">
        <div class="form-group">
            <admin-label asp-for="Age" />
            <div class="col-md-9 col-sm-9">

                @Html.Label(Model.Age.ToString())

                <span asp-validation-for="Stores"></span>
            </div>
        </div>
    </div>

    <div class="form-body">
        <div class="form-group">
            <admin-label asp-for="LevelOfEducation" />
            <div class="col-md-9 col-sm-9">

                @Html.Label(Model.LevelOfEducation)

                <span asp-validation-for="Stores"></span>
            </div>
        </div>
    </div>

    <div class="form-body">
        <div class="form-group">
            <admin-label asp-for="FieldOfStudy" />
            <div class="col-md-9 col-sm-9">

                @Html.Label(Model.FieldOfStudy)

                <span asp-validation-for="Stores"></span>
            </div>
        </div>
    </div>

    <div class="form-body">
        <div class="form-group">
            <admin-label asp-for="Address" />
            <div class="col-md-9 col-sm-9">

                @Html.Label(Model.Address)

                <span asp-validation-for="Stores"></span>
            </div>
        </div>
    </div>

    <div class="form-body">
        <div class="form-group">
            <admin-label asp-for="Job" />
            <div class="col-md-9 col-sm-9">

                @Html.Label(Model.Job)

                <span asp-validation-for="Stores"></span>
            </div>
        </div>
    </div>

    <div class="form-body">
        <div class="form-group">
            <admin-label asp-for="JobExperience" />
            <div class="col-md-9 col-sm-9">

                @Html.Label(Model.JobExperience.ToString())

                <span asp-validation-for="Stores"></span>
            </div>
        </div>
    </div>

    <div class="form-body">
        <div class="form-group">
            <admin-label asp-for="WorkAddress" />
            <div class="col-md-9 col-sm-9">

                @Html.Label(Model.WorkAddress)

                <span asp-validation-for="Stores"></span>
            </div>
        </div>
    </div>

    <div class="form-body">
        <div class="form-group">
            <admin-label asp-for="WorkTel" />
            <div class="col-md-9 col-sm-9">

                @Html.Label(Model.WorkTel)

                <span asp-validation-for="Stores"></span>
            </div>
        </div>
    </div>

    <div class="form-body">
        <div class="form-group">
            <admin-label asp-for="BusinessWebsite" />
            <div class="col-md-9 col-sm-9">

                @Html.Label(Model.BusinessWebsite)

                <span asp-validation-for="Stores"></span>
            </div>
        </div>
    </div>

    <div class="form-body">
        <div class="form-group">
            <admin-label asp-for="InstagramChannel" />
            <div class="col-md-9 col-sm-9">

                @Html.Label(Model.InstagramChannel)

                <span asp-validation-for="Stores"></span>
            </div>
        </div>
    </div>

    <div class="form-body">
        <div class="form-group">
            <admin-label asp-for="WhoDidYouGetToKnowZAP" />
            <div class="col-md-9 col-sm-9">

                @Html.Label(Model.WhoDidYouGetToKnowZAP)

                <span asp-validation-for="Stores"></span>
            </div>
        </div>
    </div>

    <div class="form-body">
        <div class="form-group">
            <admin-label asp-for="StrengthAndWeakness" />
            <div class="col-md-9 col-sm-9">

                @Html.Label(Model.StrengthAndWeakness)

                <span asp-validation-for="Stores"></span>
            </div>
        </div>
    </div>

    <div class="form-body">
        <div class="form-group">
            <admin-label asp-for="EstimateOfSell" />
            <div class="col-md-9 col-sm-9">

                @Html.Label(Model.EstimateOfSell.ToString())

                <span asp-validation-for="Stores"></span>
            </div>
        </div>
    </div>

    <div class="form-body">
        <div class="form-group">
            <admin-label asp-for="SellPromotionalProgram" />
            <div class="col-md-9 col-sm-9">

                @Html.Label(Model.SellPromotionalProgram)

                <span asp-validation-for="Stores"></span>
            </div>
        </div>
    </div>

    <div class="form-body">
        <div class="form-group">
            <admin-label asp-for="WantedCities" />
            <div class="col-md-9 col-sm-9">

                @Html.Label(Model.WantedCities)

                <span asp-validation-for="Stores"></span>
            </div>
        </div>
    </div>

</div>

Areas/Admin/Views/WidgetsCustomForm/_CreateOrUpdate.cshtml
@model CustomFormModel
<div asp-validation-summary="All"></div>
<input asp-for="Id" type="hidden" />
<admin-tabstrip name="slide-edit">
    <items>
        <tabstrip-item text="@Loc["Widgets.CustomForm.Info"]" tab-index="0">
            <content>
                <div>
                    <partial name="_CreateOrUpdate.TabInfo.cshtml" model="Model" />
                </div>
            </content>
        </tabstrip-item>        
    </items>
</admin-tabstrip>

Areas/Admin/Views/WidgetsCustomForm/_Settings.cshtml
@model ConfigurationModel

@inject Widgets.CustomForm.CustomFormWidgetSettings setting

<form method="post" id="widget-settings-form">
    <div class="panel-group">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="form-body">
                    <div class="form-group">
                        <div class="col-md-3 col-sm-3 text-right">
                            <admin-label asp-for="DisplayOrder" class="control-label" />
                        </div>
                        <div class="col-md-9 col-sm-9">
                            <admin-input asp-for="DisplayOrder" />
                        </div>
                    </div>
                    <div class="form-group">
                        <admin-label asp-for="CustomerGroups" />
                        <div class="col-md-9 col-sm-9">
                            <admin-input asp-for="CustomerGroups" />
                            <span asp-validation-for="CustomerGroups"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <admin-label asp-for="Stores" />
                        <div class="col-md-9 col-sm-9">
                            <admin-input asp-for="Stores" />
                            <span asp-validation-for="Stores"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <input type="button" id="savegeneralsettings" class="btn default" value="@Loc["Admin.Common.Save"]" />
                        <script>
                            $(function () {
                                $('#savegeneralsettings').click(function () {

                                    var postData = $(this.form).serialize();
                                    addAntiForgeryToken(postData);

                                    $.ajax({
                                        cache: false,
                                        type: 'POST',
                                        url: '@Url.Action("Configure", "WidgetsCustomForm")',
                                        data: postData,
                                        dataType: 'json',
                                        success: function (data) {
                                            alert('Saved');
                                        },
                                        error: function (xhr, ajaxOptions, thrownError) {
                                            alert('Failed to add record.');
                                        }
                                    });
                                    return false;
                                });
                            });
                        </script>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>